// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZDjhF0HHQ-ipNznyUayOS8AQD2uKLp_8',
    appId: '1:368654758817:web:4cfe7fb80e49f43e25d1e0',
    messagingSenderId: '368654758817',
    projectId: 'pelatihanmobile-46d86',
    authDomain: 'pelatihanmobile-46d86.firebaseapp.com',
    storageBucket: 'pelatihanmobile-46d86.firebasestorage.app',
    measurementId: 'G-08K2JLYGL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmfVhG_GOaLP-j-RE_ae7Ms1Bz-o2pnA8',
    appId: '1:368654758817:android:a2f75b67ae2dbf8925d1e0',
    messagingSenderId: '368654758817',
    projectId: 'pelatihanmobile-46d86',
    storageBucket: 'pelatihanmobile-46d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5VOSc9eWtTYHRPN9lnF4Ic8ytXhd2p5g',
    appId: '1:368654758817:ios:23be400276d9a4fa25d1e0',
    messagingSenderId: '368654758817',
    projectId: 'pelatihanmobile-46d86',
    storageBucket: 'pelatihanmobile-46d86.firebasestorage.app',
    iosBundleId: 'com.example.fluterApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5VOSc9eWtTYHRPN9lnF4Ic8ytXhd2p5g',
    appId: '1:368654758817:ios:23be400276d9a4fa25d1e0',
    messagingSenderId: '368654758817',
    projectId: 'pelatihanmobile-46d86',
    storageBucket: 'pelatihanmobile-46d86.firebasestorage.app',
    iosBundleId: 'com.example.fluterApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZDjhF0HHQ-ipNznyUayOS8AQD2uKLp_8',
    appId: '1:368654758817:web:2eeb98f94c1d020725d1e0',
    messagingSenderId: '368654758817',
    projectId: 'pelatihanmobile-46d86',
    authDomain: 'pelatihanmobile-46d86.firebaseapp.com',
    storageBucket: 'pelatihanmobile-46d86.firebasestorage.app',
    measurementId: 'G-3CLSWR08GW',
  );
}
